services:
  db:
    image: postgres:15
    container_name: cme_postgres
    restart: always
    environment:
      POSTGRES_DB: cme_db
      POSTGRES_USER: cme_user
      POSTGRES_PASSWORD: cme_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cme_user -d cme_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: cme_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: "postgresql://cme_user:cme_password@db/cme_db"

  frontend:
    build: ./frontend
    container_name: cme_frontend
    restart: always
    ports:
      - "3030:3000"
