version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cme_postgres
    restart: always
    environment:
      POSTGRES_DB: cme_db
      POSTGRES_USER: cme_user
      POSTGRES_PASSWORD: cme_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
