version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cme_postgres
    restart: always
    environment:
      POSTGRES_DB: cme_db
      POSTGRES_USER: cme_user
      POSTGRES_PASSWORD: cme_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: cme_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://cme_user:cme_password@db/cme_db"
